/* Generated automatically by the program `genconstants'
   from the machine description file `md'.  */

#ifndef GCC_INSN_CONSTANTS_H
#define GCC_INSN_CONSTANTS_H

#define REG_LS0 70
#define REG_LS1 71
#define S0_REGNUM 8
#define REG_LE0 68
#define REG_LE1 69
#define T0_REGNUM 5
#define S1_REGNUM 9
#define T1_REGNUM 6
#define RETURN_ADDR_REGNUM 1
#define S2_REGNUM 18
#define REG_LC0 66
#define REG_LC1 67
#define VIT_REG 72

enum unspec {
  UNSPEC_EH_RETURN = 0,
  UNSPEC_ADDRESS_FIRST = 1,
  UNSPEC_PCREL = 2,
  UNSPEC_LOAD_GOT = 3,
  UNSPEC_TLS = 4,
  UNSPEC_TLS_LE = 5,
  UNSPEC_TLS_IE = 6,
  UNSPEC_TLS_GD = 7,
  UNSPEC_AUIPC = 8,
  UNSPEC_FLT_QUIET = 9,
  UNSPEC_FLE_QUIET = 10,
  UNSPEC_COPYSIGN = 11,
  UNSPEC_LRINT = 12,
  UNSPEC_LROUND = 13,
  UNSPEC_TIE = 14,
  UNSPEC_VEC_PERM1 = 15,
  UNSPEC_VEC_PERM2 = 16,
  UNSPEC_VEC_PERM3 = 17,
  UNSPEC_VEC_PERM4 = 18,
  UNSPEC_VEC_PERM5 = 19,
  UNSPEC_VEC_PERM6 = 20,
  UNSPEC_VEC_PERM7 = 21,
  UNSPEC_VEC_PERM8 = 22,
  UNSPEC_VIT_MAX = 23,
  UNSPEC_VIT_SEL = 24,
  UNSPEC_BINS_REG = 25,
  UNSPEC_BEXTS_REG = 26,
  UNSPEC_BEXTU_REG = 27,
  UNSPEC_READSI = 28,
  UNSPEC_WRITESI = 29,
  UNSPEC_SPR_READ = 30,
  UNSPEC_SPR_WRITE = 31,
  UNSPEC_SPR_BIT_SET = 32,
  UNSPEC_SPR_BIT_CLR = 33,
  UNSPEC_FCSR_READ = 34,
  UNSPEC_FCSR_WRITE = 35,
  UNSPEC_NOP = 36,
  UNSPEC_LSETUP_END = 37,
  UNSPEC_ITU = 38,
  UNSPEC_ITS = 39,
  UNSPEC_ITH = 40,
  UNSPEC_ITM = 41,
  UNSPEC_READSI_NONVOL = 42,
  UNSPEC_MULS = 43,
  UNSPEC_MULU = 44,
  UNSPEC_MULSN = 45,
  UNSPEC_MULSRN = 46,
  UNSPEC_MULUN = 47,
  UNSPEC_MULURN = 48,
  UNSPEC_MACS = 49,
  UNSPEC_MACU = 50,
  UNSPEC_MACSN = 51,
  UNSPEC_MACSRN = 52,
  UNSPEC_MACUN = 53,
  UNSPEC_MACURN = 54,
  UNSPEC_TRUNCSIHI = 55,
  UNSPEC_TRUNCSIQI = 56,
  UNSPEC_BITREV = 57,
  UNSPEC_COMPARE_AND_SWAP = 58,
  UNSPEC_SYNC_OLD_OP = 59,
  UNSPEC_SYNC_EXCHANGE = 60,
  UNSPEC_ATOMIC_STORE = 61,
  UNSPEC_MEMORY_BARRIER = 62
};
#define NUM_UNSPEC_VALUES 63
extern const char *const unspec_strings[];

enum unspecv {
  UNSPECV_GPR_SAVE = 0,
  UNSPECV_GPR_RESTORE = 1,
  UNSPECV_FRFLAGS = 2,
  UNSPECV_FSFLAGS = 3,
  UNSPECV_BLOCKAGE = 4,
  UNSPECV_FENCE = 5,
  UNSPECV_FENCE_I = 6,
  UNSPECV_ALLOC = 7,
  UNSPECV_LC_SET = 8,
  UNSPECV_READ_EVU = 9,
  UNSPECV_OFFSETED_READ = 10,
  UNSPECV_OFFSETED_READ_HALF = 11,
  UNSPECV_OFFSETED_READ_BYTE = 12,
  UNSPECV_OFFSETED_READ_OMP = 13,
  UNSPECV_OFFSETED_WRITE = 14,
  UNSPECV_OFFSETED_WRITE_HALF = 15,
  UNSPECV_OFFSETED_WRITE_BYTE = 16,
  UNSPECV_OMP_PULP_BARRIER = 17,
  UNSPECV_OMP_PULP_CRITICAL_START = 18,
  UNSPECV_OMP_PULP_CRITICAL_END = 19,
  UNSPECV_WRITESI_VOL = 20,
  UNSPECV_READSI_VOL = 21,
  UNSPECV_SPR_READ_VOL = 22,
  UNSPECV_POINTER_ARG = 23
};
#define NUM_UNSPECV_VALUES 24
extern const char *const unspecv_strings[];

#endif /* GCC_INSN_CONSTANTS_H */
